[project]
name = "homework5"
version = "0.1.0"
description = "ML Zoomcamp week 5 homework"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "scikit-learn==1.6.1",
    "uvicorn>=0.40.0",
]
